# Generated by Django 6.0 on 2025-12-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('field_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'field',
                'ordering': ['domain', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('researcher_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=300)),
                ('total_star', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('peer_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('interest', models.TextField()),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('research_work', models.TextField(blank=True)),
                ('project', models.TextField(blank=True)),
                ('github', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert_fields', models.ManyToManyField(blank=True, related_name='expert_researchers', to='playground.field')),
            ],
            options={
                'db_table': 'researcher',
                'ordering': ['-total_star', 'name'],
            },
        ),
    ]
