# Generated by Django 6.0 on 2025-12-23 03:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingInstitution',
            fields=[
                ('institution_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'funding_institution',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('current_proceedings', models.TextField()),
                ('ongoing_work', models.TextField(blank=True)),
                ('done_work', models.TextField(blank=True)),
                ('funding_reserves', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('list_of_researchers_working', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('severity_color', models.CharField(choices=[('green', 'Low Priority'), ('yellow', 'Medium Priority'), ('orange', 'High Priority'), ('red', 'Critical Priority')], default='yellow', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'problem',
                'ordering': ['severity_color', 'name'],
            },
        ),
        migrations.AddField(
            model_name='researcher',
            name='friends',
            field=models.ManyToManyField(blank=True, to='playground.researcher'),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='conversations', to='playground.researcher')),
            ],
            options={
                'db_table': 'conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('time_date', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='playground.conversation')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='playground.researcher')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='playground.researcher')),
            ],
            options={
                'db_table': 'message',
                'ordering': ['time_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectColab',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_name', models.CharField(max_length=200)),
                ('required_skills', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_colabs', to='playground.researcher')),
            ],
            options={
                'verbose_name': 'Project Collaboration',
                'verbose_name_plural': 'Project Collaborations',
                'db_table': 'project_colab',
            },
        ),
        migrations.CreateModel(
            name='QueryPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query_type', models.CharField(choices=[('technical', 'Technical'), ('research', 'Research'), ('general', 'General')], default='general', max_length=50)),
                ('is_answered', models.BooleanField(default=False)),
                ('feedback_from', models.ManyToManyField(blank=True, related_name='feedback_queries', to='playground.researcher')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_posts', to='playground.researcher')),
            ],
            options={
                'verbose_name': 'Query Post',
                'verbose_name_plural': 'Query Posts',
                'db_table': 'query_post',
            },
        ),
        migrations.CreateModel(
            name='ResearchWork',
            fields=[
                ('work_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('author_name', models.CharField(max_length=300)),
                ('publisher', models.CharField(max_length=200)),
                ('citation', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('published', 'Published'), ('under_review', 'Under Review'), ('in_progress', 'In Progress'), ('draft', 'Draft')], default='draft', max_length=50)),
                ('vacancy_status', models.BooleanField(default=False, help_text='Open for collaboration')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('researchers', models.ManyToManyField(blank=True, related_name='research_works', to='playground.researcher')),
                ('solves_problem', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solved_by_research', to='playground.problem')),
            ],
            options={
                'db_table': 'research_work',
                'ordering': ['-citation', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('punctual_score', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('consistency', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('hard_working', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_comments', to='playground.researcher')),
                ('research_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_comments', to='playground.researchwork')),
            ],
            options={
                'verbose_name': 'Mentor Comment',
                'verbose_name_plural': 'Mentor Comments',
                'db_table': 'mentor',
            },
        ),
        migrations.CreateModel(
            name='FundingProposal',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proposal_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=50)),
                ('funding_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='playground.fundinginstitution')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_proposals_posted', to='playground.researcher')),
                ('research_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funding_proposals', to='playground.researchwork')),
            ],
            options={
                'verbose_name': 'Funding Proposal',
                'verbose_name_plural': 'Funding Proposals',
                'db_table': 'funding_proposal',
            },
        ),
        migrations.CreateModel(
            name='CoWorker',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strength', models.TextField()),
                ('hard_working', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coworker_comments', to='playground.researcher')),
                ('research_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coworker_comments', to='playground.researchwork')),
            ],
            options={
                'verbose_name': 'Co-Worker Comment',
                'verbose_name_plural': 'Co-Worker Comments',
                'db_table': 'coworker',
            },
        ),
        migrations.CreateModel(
            name='Subfield',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('field_type', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subfields', to='playground.field')),
            ],
            options={
                'db_table': 'subfield',
                'ordering': ['field', 'name'],
            },
        ),
        migrations.AddField(
            model_name='researchwork',
            name='subfield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_works', to='playground.subfield'),
        ),
        migrations.AddField(
            model_name='problem',
            name='subfield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='playground.subfield'),
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('collaboration_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('contribution_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.researcher')),
                ('funding_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.fundinginstitution')),
                ('research_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.researchwork')),
            ],
            options={
                'db_table': 'collaboration',
                'unique_together': {('researcher', 'funding_institution', 'research_work')},
            },
        ),
    ]
